name = "zeo-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
BACKEND_ORIGIN = "http://localhost:18234"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "21e5ccb52e034b4ead2781a3f0445783"
